.catalog:
  name: OpenVPN-PAM
  version: 2.3.4-1
  description: |
    OpenVPN for Rancher with PAM authentication
  minimum_rancher_version: v0.56.0
  maintainer: "Alexis Ducastel <alexis@ducastel.net>"
  uuid: openvpn-pam-0
  questions:
    - variable: "VPNPOOL_NETWORK"
      description: "VPN subnet for OpenVPN to draw client addresses from"
      label: "Network pool:"
      required: true
      default: "10.8.0.0"
      type: "string"
      
    - variable: "VPNPOOL_CIDR"
      description: "CIDR netmask for VPN subnet"
      label: "CIDR netmask:"
      required: true
      default: "24"
      type: "enum"
      options:
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
        

    - variable: "CERT_COUNTRY"
      description: "Country code part of VPN CA (2 digits only)"
      label: "Certificate Country code :"
      required: true
      default: "US"
      type: "string"
      
    - variable: "CERT_PROVINCE"
      description: "Province part of VPN CA"
      label: "Certificate Province:"
      required: true
      default: "AL"
      type: "string"

    
    - variable: "CERT_CITY"
      description: "City part of VPN CA "
      label: "Certificate City:"
      required: true
      default: "Birmingham"
      type: "string"

    - variable: "CERT_ORG"
      description: "Organization part of VPN CA "
      label: "Certificate Organization:"
      required: true
      default: "ACME"
      type: "string"
      
    - variable: "CERT_OU"
      description: "Organizational Unit part of VPN CA "
      label: "Certificate OU:"
      required: true
      default: "OPS"
      type: "string"
      
    - variable: "CERT_EMAIL"
      description: "Email part of VPN CA "
      label: "Certificate Email:"
      required: true
      default: "foo@example.com"
      type: "string"

openvpn-pam-data:
  scale: 1
openvpn-pam-server:
  scale: 1
