name: ZeroBin
description: |
  ZeroBin is a minimalist, opensource online pastebin where the server has zero knowledge of pasted data.
  Data is encrypted/decrypted in the browser using 256 bits AES.
version: 0.19-0
category: Tool
