openvpn-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  image: busybox
  volumes:
  - /etc/openvpn/

openvpn-server:
  ports:
  - 1194:1194/tcp
  environment:
    -e REMOTE_IP=1.2.3.4 \
    -e REMOTE_PORT=1194 \
    AUTH_METHOD: ${AUTH_METHOD}
    AUTH_LDAP_URL: ${AUTH_LDAP_URL}
    AUTH_LDAP_PATTERN: ${AUTH_LDAP_PATTERN}
    CERT_COUNTRY: ${CERT_COUNTRY}
    CERT_PROVINCE: ${CERT_PROVINCE}
    CERT_CITY: ${CERT_CITY}
    CERT_ORG: ${CERT_ORG}
    CERT_EMAIL: ${CERT_EMAIL}
    CERT_OU: ${CERT_OU}
    VPNPOOL_NETWORK: ${VPNPOOL_NETWORK}
    VPNPOOL_CIDR: ${VPNPOOL_CIDR}
    OPENVPN_EXTRACONF: ${OPENVPN_EXTRACONF}
  labels:
    io.rancher.sidekicks: openvpn-data
  image: mdns/rancher-openvpn:1.0
  privileged: true
  volumes_from:
  - openvpn-data
